### PR TITLE
Adding GUI-QrCodeGenerator and Calculator

### LINKED ISSUE #12: Calculator
Make a calculator using python with basic functionalities and proper GUI.

### LINKED ISSUE #13: QR Code Generator
Write a script to generate QR code in python

### LINKED ISSUE #35: Youtube video downloader
Make a GUI for downloading videos from Youtube.

### PR DESCRIPTION
**Pull request by aa-ryan**
Added GUI QR-Code-Generator.
With detailed Readme file about installation and using the scripts.
With requirements.txt file so need for manual installation of Libraries.

GUI Calculator
GUI Youtube Video Downloader

### CODE REVIEW

**Comment by aa-ryan** [comment]
Added GUI-Calculator with Readme file and Sample Image.

**Comment by aa-ryan** [comment]
Both the Projects are organised and documented.

**Comment by aa-ryan** [comment]
@sumana2001  #13 
Please have a preview of PR at this fork: 
[QrCodeGen](https://github.com/Aryan-dev007/python/tree/master/QR-Code-Generator)
[Basic_Calculator](https://github.com/Aryan-dev007/python/tree/master/Basic-Calculator) ---> if needed otherwise can be removed!

**Comment by aa-ryan** [comment]
Added Youtube Video Downloader #35

**Comment by Aniket762** [comment]
Great job with the code 🤩!

**Comment by Aniket762** [comment]
@all-contributors please add @Aryan-dev007  for code

**Pull request merged**
