### PR TITLE
Create Notepad

### PR DESCRIPTION
**Pull request by MayankDev-11**
This is a text editor,please have a look on it.

### CODE REVIEW

**Comment by Aniket762** [comment]
Hey @MayankDev-11 , some files are missing I guess can you just re-run it and add the missing files.

**Comment by MayankDev-11** [comment]
Bro you accept the pull request we will make better notepad together.What do u say?Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Aniket Pal <notifications@github.com> Date: 06/10/20  4:13 PM  (GMT+05:30) To: sumana2001/python <python@noreply.github.com> Cc: Mayank Rathi <mayank11github@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [sumana2001/python] Create Notepad (#64) 
Hey @MayankDev-11 , some files are missing I guess can you just re-run it and add the missing files.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sumana2001/python/pull/64#issuecomment-704185100",
"url": "https://github.com/sumana2001/python/pull/64#issuecomment-704185100",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MayankDev-11** [comment]
Because i am not able to give all files right nw as share as folder option is disabledSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Aniket Pal <notifications@github.com> Date: 06/10/20  4:13 PM  (GMT+05:30) To: sumana2001/python <python@noreply.github.com> Cc: Mayank Rathi <mayank11github@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [sumana2001/python] Create Notepad (#64) 
Hey @MayankDev-11 , some files are missing I guess can you just re-run it and add the missing files.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sumana2001/python/pull/64#issuecomment-704185100",
"url": "https://github.com/sumana2001/python/pull/64#issuecomment-704185100",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Review by MayankDev-11 — COMMENTED** [review]
Yep bro now check it out. I believe it is working good nw.

**Comment by MayankDev-11** [comment]
Bro sorry for the inconvinience. Now i have fixed that.

**Comment by Aniket762** [comment]
@MayankDev-11 Good job mate 😎

**Comment by Aniket762** [comment]
@all-contributors please add @MayankDev-11  for code

**Comment by MayankDev-11** [comment]
Thanks bro

**Comment by MayankDev-11** [comment]
Bro what happened why did you close it?

**Comment by MayankDev-11** [comment]
Bro is my game fine. If it is helpful plz accept the pull

**Pull request merged**
