### PR TITLE
Adding a heart disease classifier

### PR DESCRIPTION
**Pull request by ssidharths1**

### CODE REVIEW

**Comment by Aniket762** [comment]
Hey @ssidharths where is the script I guess you have only added the csv file and the readme contains nothing.

Add the files and then we can move forward!😁

**Comment by ssidharths1** [comment]
Hey there @Aniket762 , the .ipynb file was below the csv file named  Heart-Disease-Classifier/heart_disease_classifier.ipynb. readme.txt was intentionally left blank for future changes  Please do check once again & get back to me!

**Comment by Aniket762** [comment]
Thanks!

**Comment by ssidharths1** [comment]
Thanks for merging! Happy hacktober :) :100:

**Pull request merged**
