### PR TITLE
Create Readme.md

### PR DESCRIPTION
**Pull request by MayankDev-11**
This is a readme file for the snake game.

### CODE REVIEW

**Comment by Aniket762** [comment]
@MayankDev-11 great work 😍

But one request please create the pull request consisting the code and readme together

**Comment by MayankDev-11** [comment]
How should i do that
I think that u accept my pull and make a file of pygame

**Comment by MayankDev-11** [comment]
Bro is it ok to you

**Comment by Aniket762** [comment]
That's the reason I closed your pull request so that you can make a file and create the pull again

**Comment by MayankDev-11** [comment]
Chill bro thats fine. I understand

**Pull request closed without merging**
