### PR TITLE
Loan Prediction using Machine Learning #24

### LINKED ISSUE #24: Loan Prediction using Machine Learning
Loan Prediction using Machine Learning
Project idea – The idea behind this ML project is to build a model that will classify how much loan the user can take. It is based on the user’s marital status, education, number of dependents, and employments. We can build a linear model for this project.

https://www.kaggle.com/altruistdelhite04/loan-prediction-problem-dataset

### PR DESCRIPTION
**Pull request by vaderjunior**

### CODE REVIEW

**Comment by vaderjunior** [comment]
Please do look into this @sumana2001 
Thanks

**Comment by Aniket762** [comment]
Awsome job dude 😍

**Comment by Aniket762** [comment]
@all-contributors please add @vaderjunior  for code

**Comment by vaderjunior** [comment]
Hey,
Thanks @Aniket762 :D

**Pull request merged**
