### PR TITLE
Create Snake_game

### PR DESCRIPTION
**Pull request by MayankDev-11**
Bro this is a snake game made up of Pygame module. Just have a look.

### CODE REVIEW

**Comment by Aniket762** [comment]
@MayankDev-11 awsome work with the code.

It will be great if you make a directory / folder in which you add screenshot of the game window and attach a readme. You can also mention your github link in that readme file

**Comment by MayankDev-11** [comment]
K bro fine

**Comment by MayankDev-11** [comment]
Bro i made a readmeSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Aniket Pal <notifications@github.com> Date: 06/10/20  4:47 PM  (GMT+05:30) To: sumana2001/python <python@noreply.github.com> Cc: Mayank Rathi <mayank11github@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [sumana2001/python] Create Snake_game (#67) 
@MayankDev-11 awsome work with the code.
It will be great if you make a directory / folder in which you add screenshot of the game window and attach a readme. You can also mention your github link in that readme file

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sumana2001/python/pull/67#issuecomment-704200853",
"url": "https://github.com/sumana2001/python/pull/67#issuecomment-704200853",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Aniket762** [comment]
@MayankDev-11 merged

**Comment by MayankDev-11** [comment]
Thanks bro! Felt nice contributing my projects to you.
If you need any help plz contact me on my github page.

**Pull request merged**
